version: 2.1

jobs:
  test:
    parameters:
      php_version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php_version >>
    steps:
      - checkout
      - run: composer install
      - run: composer run lint
      - run: composer run test
      - store_test_results:
          path: build
      - store_artifacts:
          path: build

workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              php_version:
                - 5.6.40
                - 7.4.33
                - 8.0.30
                - 8.1.29
                - 8.2.20
                - 8.3.8
